# dashboard graphs 
# fixed data points needed 
    # y-axis : dynamic  and x axis : all datapoints in bar graph

################################################################################
# total revenue generated by the store 
    # revenue generated on till that day keeping datapoints in mind y:7 and x:5
    # orders data and product data 
################################################################################

# top selling products by revenue 5 products 
    # top 5 products globally with high revenue and total revenue of that product

# top selling products by count of sales
    # top 5 products in terms of count of sales (orders) with total number of sales

# top colleciton by revenue
    # top 5 collection with high revenue generation with revenue count  

# top collection by count of sales
    # top 5 collection with high number of sales (orders) with total number of sales 

##################################################################################
# per collection graphs
##################################################################################
# top selling products by revenue
    # top 5 selling products of that collection based on revenue in that collection 
# top selling products by count of sales
    # top 5 selling products of that collection with number of sales(orders) with total number of sales


def total_revenue_generate():
    pass
