# Generated by Django 5.1 on 2024-08-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('shop_url', models.URLField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=None, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('trial_used', models.BooleanField(default=False)),
                ('installation_date', models.DateTimeField(auto_now_add=True)),
                ('uninstall_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
