# Generated by Django 5.1.1 on 2024-09-15 13:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shop_id', models.CharField(max_length=255, unique=True)),
                ('shop_name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('shop_url', models.URLField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('trial_used', models.BooleanField(default=False)),
                ('installation_date', models.DateTimeField(auto_now_add=True)),
                ('uninstall_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=3)),
                ('createdateshopify', models.DateTimeField(blank=True, null=True)),
                ('billingAddress', models.JSONField(default=dict)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', max_length=10)),
                ('stock_location', models.CharField(choices=[('all', 'All Locations'), ('online', 'Online Locations'), ('offline', 'Offline Locations')], default='all', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SortingAlgorithm',
            fields=[
                ('algo_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCollections',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('collectionid', models.CharField(max_length=255, unique=True)),
                ('collection_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products_count', models.IntegerField(default=0)),
                ('sort_date', models.DateTimeField(blank=True, null=True)),
                ('pinned_products', models.JSONField(blank=True, null=True)),
                ('parameters_used', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('out_of_stock_down', models.BooleanField(default=False)),
                ('pinned_out_of_stock_down', models.BooleanField(default=False)),
                ('new_out_of_stock_down', models.BooleanField(default=False)),
                ('lookback_periods', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='shopify_app.client')),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.sortingalgorithm')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='default_algo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopify_app.sortingalgorithm'),
        ),
        migrations.CreateModel(
            name='SortingPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('addon_sorts_count', models.IntegerField(blank=True, null=True)),
                ('addon_sorts_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_limit', models.IntegerField(blank=True, null=True)),
                ('order_limit', models.IntegerField(blank=True, null=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopify_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='PlanHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.sortingplan')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('trial_start_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_on_trial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.sortingplan')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('sorts_count', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('addon_sorts_count', models.IntegerField(default=0)),
                ('usage_date', models.DateField()),
                ('additional_sorts_purchased', models.IntegerField(default=0)),
                ('additional_sorts_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.client')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.subscription')),
            ],
        ),
    ]
