# Generated by Django 5.1.1 on 2024-09-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_id',
            new_name='id',
        ),
    ]
