# Generated by Django 5.1.3 on 2024-11-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcollections',
            name='never_active',
            field=models.BooleanField(default=True),
        ),
    ]
