# Generated by Django 5.1.1 on 2024-10-03 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcollections',
            name='collection_total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.CreateModel(
            name='ClientGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='shop_id')),
            ],
        ),
    ]
