# Generated by Django 5.1.2 on 2024-10-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='additional_sorts_price',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='additional_sorts_purchased',
        ),
        migrations.AddField(
            model_name='subscription',
            name='charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usage',
            name='charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
