# Generated by Django 5.1 on 2024-08-31 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortingAlgorithm',
            fields=[
                ('algo_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SortingPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_monthly', models.BooleanField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_sorts_limit', models.IntegerField(blank=True, null=True)),
                ('monthly_orders_limit', models.IntegerField(blank=True, null=True)),
                ('addon_sorts_count', models.IntegerField(blank=True, null=True)),
                ('addon_sorts_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionSort',
            fields=[
                ('sort_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_id', models.CharField(max_length=255)),
                ('parameters_used', models.JSONField(default=dict)),
                ('sort_date', models.DateTimeField()),
                ('products_count', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.client')),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.sortingalgorithm')),
            ],
        ),
        migrations.CreateModel(
            name='ClientAlgoParams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_parameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.client')),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.sortingalgorithm')),
            ],
        ),
        migrations.CreateModel(
            name='PlanHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.sortingplan')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('trial_start_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_on_trial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.sortingplan')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('usage_id', models.AutoField(primary_key=True, serialize=False)),
                ('sorts_count', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('addon_sorts_count', models.IntegerField(default=0)),
                ('usage_date', models.DateField()),
                ('additional_sorts_purchased', models.IntegerField(default=0)),
                ('additional_sorts_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.client')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.subscription')),
            ],
        ),
    ]
