# Generated by Django 5.1.1 on 2024-09-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='custom_frequency_in_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='custom_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='custom_stop_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
