# Generated by Django 5.1.2 on 2024-10-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcollections',
            name='pinned_products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
