# Generated by Django 5.1.1 on 2024-09-04 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0002_sortingalgorithm_sortingplan_billing_collectionsort_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientalgoparams',
            name='algo',
        ),
        migrations.RemoveField(
            model_name='clientalgoparams',
            name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='default_algo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopify_app.sortingalgorithm'),
        ),
        migrations.AddField(
            model_name='client',
            name='schedule_frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='stock_location',
            field=models.CharField(choices=[('all', 'All Locations'), ('online', 'Online Locations'), ('offline', 'Offline Locations')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='collectionsort',
            name='actions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='collectionsort',
            name='pinned_products',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='collectionsort',
            name='review_period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collectionsort',
            name='set_criteria',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='collectionsort',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sortingplan',
            name='client_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopify_app.client'),
        ),
        migrations.AddField(
            model_name='sortingplan',
            name='cost_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sortingplan',
            name='cost_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sortingplan',
            name='order_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortingplan',
            name='sort_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.DeleteModel(
            name='ClientAlgoParams',
        ),
    ]
