# Generated by Django 5.1.2 on 2024-10-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0002_alter_clientcollections_algo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientgraph',
            old_name='client',
            new_name='shop',
        ),
        migrations.AlterField(
            model_name='client',
            name='lookback_period',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
