# Generated by Django 5.1.2 on 2024-10-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0002_remove_usage_additional_sorts_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingtokens',
            name='charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
