# Generated by Django 5.1.1 on 2024-09-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0003_remove_clientalgoparams_algo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortingplan',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='sortingplan',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='sortingplan',
            name='is_monthly',
        ),
        migrations.RemoveField(
            model_name='sortingplan',
            name='is_trial',
        ),
        migrations.RemoveField(
            model_name='sortingplan',
            name='monthly_orders_limit',
        ),
        migrations.RemoveField(
            model_name='sortingplan',
            name='monthly_sorts_limit',
        ),
    ]
