# Generated by Django 5.1.2 on 2024-10-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0003_rename_client_clientgraph_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcollections',
            name='collection_sold_units',
            field=models.IntegerField(default=0),
        ),
    ]
