# Generated by Django 5.1.1 on 2024-10-08 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0003_clientproducts_position_in_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAlgo',
            fields=[
                ('clalgo_id', models.AutoField(primary_key=True, serialize=False)),
                ('algo_name', models.CharField(max_length=255)),
                ('number_of_buckets', models.IntegerField()),
                ('boost_tags', models.JSONField(blank=True, default=list)),
                ('bury_tags', models.JSONField(blank=True, default=list)),
                ('bucket_parameters', models.JSONField(blank=True, default=dict)),
                ('applied_on_collection', models.JSONField(blank=True, default=list)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
