# Generated by Django 5.1.1 on 2024-09-26 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0003_alter_clientcollections_parameters_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProducts',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('variant_count', models.IntegerField(default=0)),
                ('revenue_generation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_inventory', models.IntegerField(default=0)),
                ('sales_velocity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.clientcollections')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('shop_id', 'collection_id', 'product_id')},
            },
        ),
    ]
