# Generated by Django 5.1.3 on 2024-11-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0003_clientproducts_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproducts',
            name='discount_percentage',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
