# Generated by Django 5.1.3 on 2024-11-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0004_alter_clientproducts_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproducts',
            name='discount_absolute',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
