# Generated by Django 5.1.1 on 2024-09-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0004_remove_sortingplan_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='member',
            field=models.BooleanField(default=False),
        ),
    ]
