# Generated by Django 5.1.2 on 2024-10-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0004_clientcollections_collection_sold_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientalgo',
            old_name='clalgo_id',
            new_name='algo_id',
        ),
    ]
