# Generated by Django 5.1.1 on 2024-10-08 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0004_clientalgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientalgo',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='shop_id'),
        ),
    ]
