# Generated by Django 5.1.1 on 2024-10-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0005_alter_clientalgo_shop_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientalgo',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
