# Generated by Django 5.1.1 on 2024-09-10 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0006_client_billingaddress_client_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectionid', models.CharField(max_length=255, unique=True)),
                ('collection_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products_count', models.IntegerField(default=0)),
                ('sort_date', models.DateTimeField(blank=True, null=True)),
                ('pinned_products', models.JSONField(blank=True, null=True)),
                ('parameters_used', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('algo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify_app.sortingalgorithm')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='shopify_app.client')),
            ],
        ),
        migrations.DeleteModel(
            name='CollectionSort',
        ),
    ]
