# Generated by Django 5.1.1 on 2024-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0007_clientcollections_delete_collectionsort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcollections',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
