# Generated by Django 5.1.1 on 2024-09-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app', '0008_alter_clientcollections_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcollections',
            name='lookback_periods',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientcollections',
            name='new_out_of_stock_down',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientcollections',
            name='out_of_stock_down',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientcollections',
            name='pinned_out_of_stock_down',
            field=models.BooleanField(default=False),
        ),
    ]
